version: '3'

services:
 wboardservice:
    image: wom/w-board-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    networks:
        backend:
         aliases:
             - "wboardservice"
             
 networks:
  backend:
   driver: bridge
